In [2]:
import pandas as pd

**Q2. Create a Pandas Series from a list of student marks [65, 70, 85, 90, 55] with custom index labels
as student names.
 Calculate the average marks.
 Identify students who scored more than 75.**

In [3]:
data={
    "ID" : [101,102,103,104,105],
    "Name":["Arun","Fadhil","Praveen","Koushik","Tharun"],
    "Marks":[65, 70, 85, 90, 55]
}

df=pd.DataFrame(data)
df

ID     Name  Marks
0  101     Arun     65
1  102   Fadhil     70
2  103  Praveen     85
3  104  Koushik     90
4  105   Tharun     55

In [4]:
#average marks
d=df["Marks"].mean()
print("Average marks:",d)

Average marks: 73.0


In [5]:
#student who scored > 75
df[df["Marks"]>75]

ID     Name  Marks
2  103  Praveen     85
3  104  Koushik     90

**Q2. Create a DataFrame for 5 employees with columns: [&#39;EmpID&#39;, &#39;Name&#39;, &#39;Department&#39;, &#39;Salary&#39;].
 Display the data types of all columns.
 Add a new column called Bonus as 10% of the Salary.**

In [6]:
emp={
    "EMP ID":[101,102,103,104,105],
    "Name":["Arun","Fadhil","Praveen","Koushik","Tharun"],
    "Department":["IT","HR","IT","HR","IT"],
    "Salary":[50000,60000,55000,70000,65000]
}

empd=pd.DataFrame(emp)
empd

EMP ID     Name Department  Salary
0     101     Arun         IT   50000
1     102   Fadhil         HR   60000
2     103  Praveen         IT   55000
3     104  Koushik         HR   70000
4     105   Tharun         IT   65000

In [7]:
# displaying the all columns datatypes

empd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   EMP ID      5 non-null      int64 
 1   Name        5 non-null      object
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes


In [8]:
#add new column named bonus with 10% bonus of salary
empd["Bonus"]=empd["Salary"]*0.10
empd

EMP ID     Name Department  Salary   Bonus
0     101     Arun         IT   50000  5000.0
1     102   Fadhil         HR   60000  6000.0
2     103  Praveen         IT   55000  5500.0
3     104  Koushik         HR   70000  7000.0
4     105   Tharun         IT   65000  6500.0

1. NumPy Arrays, Indexing, Broadcasting
Q1. Create a 5x5 NumPy array of integers from 0 to 24.
 Extract the second row and third column using indexing.
 Replace all odd numbers with -1 using broadcasting.
Q2. Generate a 3D NumPy array of shape (2, 3, 4) filled with random integers between 10 and 50.
 Use slicing to extract the last 2 elements from each inner-most array.
 Broadcast a scalar value (e.g., subtract 10 from all elements).

In [9]:
import numpy as np

In [10]:
array= np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
ar=np.reshape(array,(5,5))
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
#Extract the second row and third column using indexing.

ext= ar[1]
print("2nd row:",ext)

ext1=ar[:,2]
print("3rd column:",ext1)


2nd row: [5 6 7 8 9]
3rd column: [ 2  7 12 17 22]


In [13]:
#Replace all odd numbers with -1 using broadcasting.

odd = (ar % 2) != 0
print(odd)

# Use the mask to assign -1 to all elements that are odd
ar[odd]=-1
ar

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1],
       [20, -1, 22, -1, 24]])

Generate a 3D NumPy array of shape (2, 3, 4) filled with random integers between 10 and 50.
 Use slicing to extract the last 2 elements from each inner-most array.
 Broadcast a scalar value (e.g., subtract 10 from all elements).

In [14]:
#Generate a 3D NumPy array of shape (2, 3, 4) filled with random integers between 10 and 50
arr=np.random.randint(10,50,size=(2,3,4))
arr

array([[[22, 18, 25, 41],
        [17, 46, 18, 35],
        [34, 13, 23, 40]],

       [[26, 25, 27, 20],
        [30, 44, 38, 34],
        [20, 16, 24, 46]]])

In [15]:
 #Use slicing to extract the last 2 elements from each inner-most array.

slice_arr=arr[:,:,2:]
slice_arr

array([[[25, 41],
        [18, 35],
        [23, 40]],

       [[27, 20],
        [38, 34],
        [24, 46]]])

In [16]:
#Broadcast a scalar value (e.g., subtract 10 from all elements)

b=10
c=arr-10
print(c)

[[[12  8 15 31]
  [ 7 36  8 25]
  [24  3 13 30]]

 [[16 15 17 10]
  [20 34 28 24]
  [10  6 14 36]]]
